# Generated by Django 5.2.5 on 2025-09-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='meesage',
            new_name='message',
        ),
    ]
