# Generated by Django 5.2.6 on 2025-09-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_options_comment_loging_require'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='loging_require',
        ),
        migrations.AddField(
            model_name='post',
            name='loging_require',
            field=models.BooleanField(default=False),
        ),
    ]
