# Generated by Django 5.2.6 on 2025-09-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_loging_require_post_loging_require'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='loging_require',
            new_name='login_require',
        ),
    ]
